Company.FirstProject.PL/Controllers/DepartmentController.cs
using AutoMapper;
using Company.FirstProject.BLL.Interfaces;
using Company.FirstProject.BLL.Repositoris;
using Company.FirstProject.DAL.Models;
using Company.FirstProject.PL.DTOS;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Company.FirstProject.PL.Controllers
{
    [Authorize]

    public class DepartmentController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        //private readonly IDepartmentRepository _departmentRepository;
        private readonly IMapper _mapper;

        public DepartmentController(
            //IDepartmentRepository departmentRepository,
            IUnitOfWork unitOfWork,
            IMapper Mapper

            )
        {
            _unitOfWork = unitOfWork;
            //_departmentRepository = departmentRepository;
            _mapper = Mapper;
        }
        [HttpGet] // Get : /Department/Index
        public async Task<IActionResult> Index()
        {
            var departmets = await _unitOfWork.DepartmentRepository.GetAllAsync();
            return View(departmets);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]

        public async Task<IActionResult> Create(CreateDepartmentDto model)
        {
            if (ModelState.IsValid)
            {
                try
                {

                    var department = _mapper.Map<Department>(model);
                     await _unitOfWork.DepartmentRepository.AddAsync(department);
                    var count =await _unitOfWork.CompleteAsync();
                    if (count > 0)
                    {
                        TempData["Message"] = "Department is Created";
                        return RedirectToAction(nameof(Index));
                    }
                }
                catch (Exception ex)
                {
                    ModelState.AddModelError("", ex.Message);

                }
            }
            return View(model);
        }

        [HttpGet]

        // Refactore Code 
        public async Task<IActionResult> Details(int? id ,string ViewName="Details")
        {
            if (id is null) return BadRequest("Invalid Id "); //400
            var department =await _unitOfWork.DepartmentRepository.GetAsync(id.Value);
            if (department is null) return NotFound(new { statscode = 400, message = $"Departmen With ID :{id} is not found" });
            return View( ViewName,department);
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id is null) return BadRequest("Invalid Id ");
            var department =await _unitOfWork.DepartmentRepository.GetAsync(id.Value);
            if (department is null) return NotFound(new { statscode = 400, message = $"employee With ID :{id} is not found" });
            var dto = _mapper.Map<CreateDepartmentDto>(department);

            return View(dto);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit([FromRoute] int id, CreateDepartmentDto model)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    var department = _mapper.Map<Department>(model); // AutoMapper Conversion
                    department.Id = id; // Ensure the ID remains correct

                    _unitOfWork.DepartmentRepository.Update(department);
                    var count =await _unitOfWork.CompleteAsync();
                    if (count > 0)
                    {
                        return RedirectToAction(nameof(Index));
                    }
                }
                catch (Exception ex)
                {
                    ModelState.AddModelError("", ex.Message);
                }
            }
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(int id)
        {
            var department = await _unitOfWork.DepartmentRepository.GetAsync(id);
            if (department != null)
            {
                 _unitOfWork.DepartmentRepository.Delete(department);
                var count =await _unitOfWork.CompleteAsync();
                if (count > 0)
                {
                    return RedirectToAction(nameof(Index)); // Redirect instead of returning a view
                }
            }

            return RedirectToAction(nameof(Index)); // Redirect even if the delete fails
        }
    }
}

Company.FirstProject.PL/Views/Department/Create.cshtml
@model CreateDepartmentDto


<h1>Create Departmen</h1>
<br />
<br />

<form asp-action="Create">

    <partial name="CreateAndEditPartialView/_CreateAndEdit" />

    <div class="my-3">

        <input  type="submit" value="Create" class="btn btn-primary"/>
        <a asp-action="Index" class="btn btn-Light">Back To List</a>
    </div>
</form>
@section ValidationSection {
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
}

Company.FirstProject.PL/Views/Department/Details.cshtml
@model Department
@{
    ViewData["Title"] = "Details";
}

<h1>Details Page</h1>

<br />
<br />

<form asp-action="Edit">
    <div class="row g-2">
        <div class="col-md">
            <div class="form-floating">
                <input readonly asp-for="Code" class="form-control" />
                <label asp-for="Code" class="col-form-label"></label>

            </div>
        </div>
        <div class="col-md">
            <div class="form-floating">
                <input readonly asp-for="Name" class="form-control" />
                <label asp-for="Name" class="col-form-label"></label>

            </div>
        </div>
         <div class="col-md">
            <div class="form-floating">
                <input readonly asp-for="CreateAt" class="form-control" />
                <label asp-for="CreateAt" class="col-form-label"></label>
                </div>
         </div>
     </div>

</form>

<div class="my-3">
    <a asp-action="Edit" asp-route-id="@Model.Id" asp-controller="Department" class="btn btn-warning">Edit</a>
    <a asp-controller="Department" asp-action="Index" class="btn btn-light">Back To List</a>
</div>

Company.FirstProject.PL/Views/Department/Edit.cshtml
@model CreateDepartmentDto 
@{
    ViewData["Title"] = "Edit";
}

<h1>Edit Department </h1>

<br />
<br />


<form asp-action="Edit">

    <partial name="CreateAndEditPartialView/_CreateAndEdit" />

    <div class="my-3">

        <input type="submit" value="Edit" class="btn btn-warning" />
        <a asp-action="Index" class="btn btn-Light">Back To List</a>
    </div>
</form>
@section ValidationSection {
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
}

Company.FirstProject.PL/Views/Department/Index.cshtml
@model IEnumerable<Department>
@{
    ViewData["Title"] = "Index";
}

<h1> All Department </h1>

<br/>
<br/>

<a asp-action="Create" asp-controller="Department" class="btn btn-primary">Create Department</a>

<br/>
<br />

@if (Model.Count()  >  0){
    <table class=" table table-hover table-striped">
        <thead>
            <tr>
                <th>Code</th>
                <th>Name</th>
                <th>Date Of Creation</th>
                <th>Details</th>
                <th>Update</th>
                <th>Delete</th>
            </tr>
        </thead>
      <tbody>
          @foreach(var item in Model){
              <tr>
                  <td>@item.Code</td>
                  <td>@item.Name</td>
                  <td>@item.CreateAt</td>
                  <td>
                        <a asp-action="Details" asp-route-id="@item.Id" class="btn btn-warning">Details</a>
                  </td>
                    <td>
                        <a asp-action="Edit" asp-route-id="@item.Id" class="btn btn-success">Update</a>
                    </td>
                    <td>
                        <form asp-action="Delete" asp-controller="Department" method="post" onsubmit="return confirm('Are you sure you want to delete this?');">
                            @Html.AntiForgeryToken()
                            <input type="hidden" name="id" value="@item.Id" />
                            <button type="submit" class="btn btn-danger">Delete</button>
                        </form>
                    </td>
              </tr>
          }
      </tbody>
    </table>
}else {
   <div class="mt-4 alert alert-info">
       There Are No Department :(
   </div>
}